version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html # Mount source code
    environment:
      APP_ENV: dev

  db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - mongo:/data/db
    secrets:
      - db-password

volumes:
  mongo:

secrets:
  db-password:
    file: ./db/password.txt
